name: Tests

on:
  push:
    branches:
      - master
      - wild_goose

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Compile and install libomp from source
        run: ./scripts/install-libomp-macos.sh
      - name: Install Python packages
        run: |
          python3 -m pip install --extra-index-url https://test.pypi.org/simple energyflow==1.3.3a0
          python3 -m pip install .[test] pytest
      - name: Test package
        run: pytest wasserstein
