name: Tests

on:
  push:
    branches:
      - master
      - fix/libomp-install
  workflow_call:
    inputs:
      plan:
        required: true
        type: string
  pull_request:
    paths:
      - pyproject.toml
      - .github/workflows/build-wheels.yml
      - .github/workflows/ci.yml

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout LLVM-OpenMP
        uses: actions/checkout@v4
        with: 
          repository: llvm/llvm-project
          ref: llvmorg-18.1.6
          sparse-checkout: openmp

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python packages
        run: |
          python3 -m pip install --extra-index-url https://test.pypi.org/simple energyflow==1.3.3a0
          python3 -m pip install .[test] pytest
      - name: Test package
        run: pytest wasserstein
