name: Tests

on:
  push:
    branches:
      - master
      - fix/libomp-install
  workflow_call:
    inputs:
      plan:
        required: true
        type: string
  pull_request:
    paths:
      - pyproject.toml
      - .github/workflows/build-wheels.yml
      - .github/workflows/ci.yml

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1

      - name: Upload wheels to GH
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheel
          path: wheelhouse/*.whl