name: Publish

on:
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    environment:
      name: pypi
      url: https://pypi.org/p/Wasserstein
    permissions:
      id-token: write
    steps:
      - name: Download wheels from GH
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Upload package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
